# Generated by Django 5.2.4 on 2025-07-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('security', 'Security'), ('account', 'Account'), ('investment', 'Investment'), ('loan', 'Loan'), ('bill', 'Bill'), ('card_application', 'Card Application'), ('system', 'System')], max_length=20),
        ),
    ]
