# Generated by Django 4.2.22 on 2025-11-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_lock_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='unlock_request_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unlock_request_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='unlock_request_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
