# Generated by Django 5.2.4 on 2025-07-27 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bitcoin_balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='bitcoin_qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bitcoin_wallet_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='BitcoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('send', 'Send'), ('receive', 'Receive')], max_length=10)),
                ('balance_source', models.CharField(choices=[('fiat', 'Fiat Balance'), ('bitcoin', 'Bitcoin Balance')], max_length=10)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_btc', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bitcoin_price_at_time', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recipient_wallet_address', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('transaction_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('blockchain_tx_id', models.CharField(blank=True, max_length=100)),
                ('confirmation_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitcoin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bitcoin_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
