# Generated by Django 5.2.4 on 2025-08-03 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_failed_pin_attempts_user_pin_locked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcointransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_bitcoin_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='bitcointransaction',
            table='account_bitcoin_transactions',
        ),
    ]
