# Generated by Django 4.2.22 on 2025-10-04 02:10

import bitcoin_wallet.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingBitcoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(help_text='Bitcoin transaction hash', max_length=100, unique=True)),
                ('amount_btc', models.DecimalField(decimal_places=8, help_text='Amount in Bitcoin', max_digits=18)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=12)),
                ('sender_address', models.CharField(help_text="Sender's Bitcoin address", max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('confirmation_count', models.IntegerField(default=0, help_text='Number of blockchain confirmations')),
                ('required_confirmations', models.IntegerField(default=3, help_text='Required confirmations for completion')),
                ('block_height', models.IntegerField(blank=True, help_text='Block height when transaction was included', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this transaction')),
                ('is_manually_approved', models.BooleanField(default=False, help_text='Whether admin manually approved this transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_bitcoin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incoming Bitcoin Transaction',
                'verbose_name_plural': 'Incoming Bitcoin Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencySwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_type', models.CharField(choices=[('usd_to_btc', 'USD to Bitcoin'), ('btc_to_usd', 'Bitcoin to USD')], help_text='Type of currency swap', max_length=20)),
                ('amount_from', models.DecimalField(decimal_places=8, help_text='Amount being swapped from', max_digits=18)),
                ('amount_to', models.DecimalField(decimal_places=8, help_text='Amount being swapped to', max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=8, help_text='Exchange rate at time of swap', max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Unique transaction identifier', max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_currency_swaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency Swap',
                'verbose_name_plural': 'Currency Swaps',
                'db_table': 'wallet_currency_swaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BitcoinWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(blank=True, help_text='Bitcoin wallet address', max_length=100)),
                ('qr_code', models.ImageField(blank=True, help_text='QR code image for the wallet address', null=True, upload_to=bitcoin_wallet.models.qr_code_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitcoin_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitcoin Wallet',
                'verbose_name_plural': 'Bitcoin Wallets',
            },
        ),
    ]
