# Generated by Django 4.2.22 on 2025-12-02 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bitcoin_wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingBitcoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_source', models.CharField(choices=[('fiat', 'Fiat Balance'), ('bitcoin', 'Bitcoin Balance')], default='fiat', help_text='Source of funds', max_length=10)),
                ('recipient_wallet_address', models.CharField(help_text="Recipient's Bitcoin address", max_length=100)),
                ('amount_btc', models.DecimalField(decimal_places=8, help_text='Amount in Bitcoin', max_digits=18)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Amount in USD (if paid from fiat)', max_digits=12, null=True)),
                ('bitcoin_price_at_time', models.DecimalField(decimal_places=2, help_text='Bitcoin price at transaction time', max_digits=12)),
                ('transaction_fee', models.DecimalField(decimal_places=8, default=1e-05, help_text='Network transaction fee in BTC', max_digits=18)),
                ('transaction_hash', models.CharField(blank=True, help_text='Bitcoin transaction hash', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_bitcoin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outgoing Bitcoin Transaction',
                'verbose_name_plural': 'Outgoing Bitcoin Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
