# Generated by Django 4.2.22 on 2025-12-03 09:34

from django.db import migrations
import hashlib
import uuid


def fill_missing_transaction_hashes(apps, schema_editor):
    """Fill any existing null/blank transaction_hash values before making field non-null"""
    OutgoingBitcoinTransaction = apps.get_model('bitcoin_wallet', 'OutgoingBitcoinTransaction')
    
    # Find all records with empty transaction_hash
    transactions_without_hash = OutgoingBitcoinTransaction.objects.filter(
        transaction_hash__in=['', None]
    )
    
    for transaction in transactions_without_hash:
        # Generate unique hash for existing records using UUID for uniqueness
        unique_id = uuid.uuid4()
        data = f"{transaction.user_id}{transaction.recipient_wallet_address}{transaction.amount_btc}{transaction.id}{unique_id}"
        transaction.transaction_hash = hashlib.sha256(data.encode()).hexdigest()
        transaction.save(update_fields=['transaction_hash'])


def reverse_fill(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_wallet', '0002_outgoingbitcointransaction'),
    ]

    operations = [
        migrations.RunPython(fill_missing_transaction_hashes, reverse_fill),
    ]
