# Generated by Django 5.2.4 on 2025-07-28 12:05

import bitcoin_wallet.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_wallet', '0002_currencyswap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinwallet',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR code image for the wallet address', null=True, upload_to=bitcoin_wallet.models.qr_code_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='bitcoinwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitcoin_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomingbitcointransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_bitcoin_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
