# Generated by Django 4.2.22 on 2025-12-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_wallet', '0003_fill_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingbitcointransaction',
            name='transaction_hash',
            field=models.CharField(help_text='Bitcoin transaction hash', max_length=100, unique=True),
        ),
    ]
