# Generated by Django 5.2.4 on 2025-07-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_wallet', '0003_alter_bitcoinwallet_qr_code_alter_bitcoinwallet_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyswap',
            name='amount_from',
            field=models.DecimalField(decimal_places=2, help_text='Amount being swapped from', max_digits=18),
        ),
        migrations.AlterField(
            model_name='currencyswap',
            name='amount_to',
            field=models.DecimalField(decimal_places=2, help_text='Amount being swapped to', max_digits=18),
        ),
    ]
