# Generated by Django 5.2.4 on 2025-07-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_wallet', '0004_alter_currencyswap_amount_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyswap',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, help_text='Exchange rate at time of swap', max_digits=20),
        ),
    ]
