# Generated by Django 5.2.4 on 2025-07-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_wallet', '0005_alter_currencyswap_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyswap',
            name='amount_from',
            field=models.DecimalField(decimal_places=8, help_text='Amount being swapped from', max_digits=18),
        ),
        migrations.AlterField(
            model_name='currencyswap',
            name='amount_to',
            field=models.DecimalField(decimal_places=8, help_text='Amount being swapped to', max_digits=18),
        ),
        migrations.AlterField(
            model_name='currencyswap',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, help_text='Exchange rate at time of swap', max_digits=20),
        ),
    ]
