# Generated by Django 5.2.4 on 2025-08-03 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin_wallet', '0006_alter_currencyswap_amount_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyswap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_currency_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='currencyswap',
            table='wallet_currency_swaps',
        ),
    ]
