# Generated by Django 5.2.4 on 2025-07-29 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('preferred_daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('estimated_completion_date', models.DateField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='virtualcard',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_card', to='banking.cardapplication'),
        ),
    ]
