# Generated by Django 4.2.22 on 2025-12-02 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0002_transfer_admin_approved_transfer_admin_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_number_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='routing_number_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='directdeposit',
            name='account_number_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='directdeposit',
            name='routing_number_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='virtualcard',
            name='card_number_hash',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='routing_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='directdeposit',
            name='account_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='directdeposit',
            name='routing_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(choices=[('internal', 'Internal Transfer'), ('ach', 'ACH Transfer'), ('wire_domestic', 'Wire Transfer (Domestic)'), ('wire_international', 'Wire Transfer (International)'), ('external', 'External Transfer'), ('instant', 'Instant Transfer')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='card_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='cvv',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.CreateModel(
            name='SavedBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('transfer_type', models.CharField(choices=[('ach', 'ACH Transfer'), ('wire_domestic', 'Wire Transfer (Domestic)'), ('wire_international', 'Wire Transfer (International)')], max_length=30)),
                ('recipient_name', models.CharField(max_length=200)),
                ('account_number', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('account_number_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('routing_number', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('routing_number_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('account_type', models.CharField(blank=True, max_length=20)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('swift_code', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_address', models.TextField(blank=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_beneficiaries',
                'ordering': ['-last_used', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=200)),
                ('account_number', encrypted_model_fields.fields.EncryptedCharField()),
                ('account_number_hash', models.CharField(db_index=True, default='', max_length=64)),
                ('routing_number', encrypted_model_fields.fields.EncryptedCharField()),
                ('routing_number_hash', models.CharField(db_index=True, default='', max_length=64)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=20)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_address', models.TextField(blank=True)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_bank_accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
