# Generated by Django 4.2.22 on 2025-12-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_checkdeposit'),
        ('banking', '0004_alter_cardapplication_status_checkdeposit'),
    ]

    operations = [
    ]
