# Generated by Django 4.2.22 on 2025-12-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_merge_20251209_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkdeposit',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='check_deposits/back/'),
        ),
    ]
