# Generated by Django 5.2.4 on 2025-08-03 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loan',
            new_name='loan_app_lo_user_id_8d4aff_idx',
            old_name='loans_user_id_efac20_idx',
        ),
        migrations.RenameIndex(
            model_name='loan',
            new_name='loan_app_lo_loan_ty_7a7a83_idx',
            old_name='loans_loan_ty_7d36ad_idx',
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_app_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_app_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='loan',
            table='loan_app_loans',
        ),
        migrations.AlterModelTable(
            name='loanapplication',
            table='loan_app_applications',
        ),
    ]
