# Generated by Django 4.2.22 on 2025-12-05 11:44

from django.db import migrations, models


def copy_amount_to_amount_invested(apps, schema_editor):
    """
    Copy existing 'amount' values to 'amount_invested' before removing the old field.
    This preserves existing investment data.
    """
    Investment = apps.get_model('transactions', 'Investment')
    for investment in Investment.objects.all():
        # Copy amount to amount_invested if amount exists
        if hasattr(investment, 'amount') and investment.amount is not None:
            investment.amount_invested = investment.amount
            investment.save(update_fields=['amount_invested'])


def reverse_copy_amount(apps, schema_editor):
    """
    Reverse migration: copy amount_invested back to amount.
    """
    Investment = apps.get_model('transactions', 'Investment')
    for investment in Investment.objects.all():
        if hasattr(investment, 'amount_invested') and investment.amount_invested is not None:
            investment.amount = investment.amount_invested
            investment.save(update_fields=['amount'])


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        # Step 1: Add new field with null=True to allow existing rows
        migrations.AddField(
            model_name='investment',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, null=True, blank=True, help_text='Total amount invested in USD', max_digits=15),
        ),
        # Step 2: Copy data from old field to new field
        migrations.RunPython(copy_amount_to_amount_invested, reverse_copy_amount),
        # Step 3: Set default value and make non-nullable
        migrations.AlterField(
            model_name='investment',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount invested in USD', max_digits=15),
        ),
        # Step 4: Now safe to remove old fields
        migrations.RemoveField(
            model_name='investment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='return_rate',
        ),
        migrations.AddField(
            model_name='investment',
            name='balance_source',
            field=models.CharField(choices=[('fiat', 'Fiat Balance'), ('bitcoin', 'Bitcoin Balance')], default='fiat', max_length=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='current_price_per_unit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current total value in USD', max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='name',
            field=models.CharField(default='Unknown Investment', help_text='Investment name (e.g., Apple Inc.)', max_length=200),
        ),
        migrations.AddField(
            model_name='investment',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Price per share/unit at purchase', max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit or loss amount', max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='profit_loss_percentage',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Profit or loss percentage', max_digits=10),
        ),
        migrations.AddField(
            model_name='investment',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=1, help_text='Number of shares/units', max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='symbol',
            field=models.CharField(blank=True, default='', help_text='Stock/Crypto symbol (e.g., AAPL)', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_dfa5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investment_type', 'symbol'], name='investments_investm_740ba6_idx'),
        ),
    ]
