# Generated by Django 5.2.4 on 2025-08-03 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('bitcoin_address', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction_bitcoin_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencySwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_from', models.CharField(max_length=10)),
                ('currency_to', models.CharField(max_length=10)),
                ('amount_from', models.DecimalField(decimal_places=8, max_digits=15)),
                ('amount_to', models.DecimalField(decimal_places=8, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transaction_currency_swaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('mortgage', 'Mortgage'), ('auto', 'Auto Loan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction_loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='bills_user_id_1151fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='bills_biller__de3f67_idx',
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='investments_user_id_74659d_idx',
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='investments_status_9fccfa_idx',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='biller_category',
            new_name='bill_type',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='price_per_share',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='biller_name',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='recurring_frequency',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='action',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bill',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='return_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('stocks', 'Stocks'), ('bonds', 'Bonds'), ('mutual_funds', 'Mutual Funds'), ('etfs', 'ETFs'), ('crypto', 'Cryptocurrency')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='bitcointransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitcoin_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyswap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
