# Generated by Django 5.2.10 on 2026-01-23 09:39

from django.db import migrations, models


def backfill_biller_category(apps, schema_editor):
    Bill = apps.get_model('transactions', 'Bill')
    for bill in Bill.objects.all():
        if bill.bill_type:
            bill.biller_category = bill.bill_type
            bill.save()

def reverse_backfill_biller_category(apps, schema_editor):
    Bill = apps.get_model('transactions', 'Bill')
    for bill in Bill.objects.all():
        if bill.biller_category:
            bill.bill_type = bill.biller_category
            bill.save()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_investment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='biller_category',
            field=models.CharField(choices=[('utilities', 'Utilities'), ('insurance', 'Insurance'), ('subscription', 'Subscription'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.RunPython(backfill_biller_category, reverse_backfill_biller_category),
        migrations.AddField(
            model_name='bill',
            name='biller_name',
            field=models.CharField(default='Unknown Biller', max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('utilities', 'Utilities'), ('insurance', 'Insurance'), ('subscription', 'Subscription'), ('credit_card', 'Credit Card'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
